# Colors
BG_COLOR = "#FFF"
DROP_DOWN_BG_COLOR = "#EEE"
TEXT_COLOR = "#444"
BORDER_COLOR = "#DDD"
# BUTTON_COLOR = "#ffa94d"
# BUTTON_HOVER_COLOR = "#ffc382"
# MEAL_OPTION_HEADER = "#ffcb94"
BUTTON_COLOR = "#f4a261"
BUTTON_HOVER_COLOR = "#f5ab71"
MEAL_OPTION_HEADER = "#f6b581"
BUTTON_TEXT_COLOR = "#FFF"
MEAL_OPTION_BG_COLOR = "#EEE"
GREEN = "#2a9d8f"
DARK_GREEN = "#264653"
YELLOW = "#e9c46a"
ORANGE = "#f4a261"
RED = "#e76f51"

# Fonts
FAMILY = "helvetica"

# Sizes
HEADER_PADY_TOP = 20
HEADER_PADY_BOT = 10
MEAL_OPTION_HEIGHT = 80
DATA_PADX = 10
DATA_PADY_TOP = 25
DATA_PADY = 10
BORDER_WIDTH = 1
